version: '2'
services:
    devplatform-app:
        image: devplatform
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://devplatform-mysql:3306/devplatform?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    devplatform-mysql:
        extends:
            file: mysql.yml
            service: devplatform-mysql
